In [1]:
import numpy as np
import pandas as pd
import sqlite3

conn = sqlite3.connect('../data/lafc_content.db')

In [2]:
query = '''
SELECT name
FROM sqlite_master
WHERE type= 'table'
'''

pd.read_sql_query(query, conn)

                 name
0   channel_snapshots
1              videos
2               teams
3             matches
4  standings_official
5  lafc_match_context
6   classified_videos
7           playlists
8      playlist_items
9          video_tabs

In [11]:
query = '''
SELECT *
FROM video_tabs
'''

df = pd.read_sql_query(query, conn)

df.groupby('tab').count()

            video_id  fetched_at
tab
horizontal      3006        3006
live             103         103
short            539         539

In [19]:
query='''
SELECT *
FROM playlists
'''

df = pd.read_sql_query(query, conn)
df

,playlist_id,channel_id,title,description,item_count,fetched_at
0,PLnNotX5RheZh4wmHBwGvbAkJRfErHyrrW,UCnqj91wjXAT0bsmxF1fHWBA,Annyeong LAFC,,16,2026-08-13T18:43:58.156432+00:00
1,PLnNotX5RheZjSscQY1tTzf_ugBj6arubg,UCnqj91wjXAT0bsmxF1fHWBA,The Son Spotlight,Watch every moment of Son Heung-Min's journey ...,74,2026-08-13T18:43:58.156432+00:00
2,PLnNotX5RheZhqZ_9MDV8mV4S-FQII8AKe,UCnqj91wjXAT0bsmxF1fHWBA,Black & Gold Insider,Go inside the LAFC locker room with host Max B...,60,2026-08-13T18:43:58.156432+00:00
3,PLnNotX5RheZiJEQSDMwAs2BreZ2ymtyeu,UCnqj91wjXAT0bsmxF1fHWBA,The Vela Vault,"All the highlights, interviews, features and m...",27,2026-08-13T18:43:58.156432+00:00
4,PLnNotX5RheZiZGlnfam05pUNrvB_vQDKD,UCnqj91wjXAT0bsmxF1fHWBA,LAFC's MLS All-Stars,All the happenings around LAFC players who are...,1,2026-08-13T18:43:58.156432+00:00
5,PLnNotX5RheZiZeXTJECsf9sunPbALEem4,UCnqj91wjXAT0bsmxF1fHWBA,Match Previews,Get the inside scoop on LAFC ahead of every ma...,77,2026-08-13T18:43:58.156432+00:00
6,PLnNotX5RheZgkPl6JSxyomK6VcHFmIsaE,UCnqj91wjXAT0bsmxF1fHWBA,Adventures in the U.S. Open Cup,LAFC's coaches and players have a strong affin...,54,2026-08-13T18:43:58.156432+00:00
7,PLnNotX5RheZhlMGwy3Ski8w74tL6FfrE3,UCnqj91wjXAT0bsmxF1fHWBA,Full Matches,Watch full LAFC matches from preseason scrimma...,9,2026-08-13T18:43:58.156432+00:00
8,PLnNotX5RheZjNwCuvj6YBT1t_2St7un30,UCnqj91wjXAT0bsmxF1fHWBA,Off the Pitch | Presented by Waymo,Go one-on-one with players and coaches in this...,20,2026-08-13T18:43:58.156432+00:00
9,PLnNotX5RheZiYLft4Fnsza7TE9owtTiyR,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Player Profiles - 2024,LAFC's 2024 Player Profiles introduce the many...,8,2026-08-13T18:43:58.156432+00:00
10,PLnNotX5RheZh8hboDszHaMBtORRmrGmPL,UCnqj91wjXAT0bsmxF1fHWBA,Anatomy of a Goal,When the Black & Gold score a magnificent goal...,7,2026-08-13T18:43:58.156432+00:00
11,PLnNotX5RheZgmbdA_z1ucAU8ysmb7lOZ_,UCnqj91wjXAT0bsmxF1fHWBA,LAFC+,You know Dave Denholm and Mario Ruiz from the ...,108,2026-08-13T18:43:58.156432+00:00
12,PLnNotX5RheZh6fWExobLCcDjosiKDjfyQ,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Weekly,Take a weekly dive into everything going on wi...,83,2026-08-13T18:43:58.156432+00:00
13,PLnNotX5RheZiQm6-lhgbecnaBZIbV12e2,UCnqj91wjXAT0bsmxF1fHWBA,The LAFC Academy,Get an inside look at the players coming throu...,14,2026-08-13T18:43:58.156432+00:00
14,PLnNotX5RheZjPnbiQOF5h5QT__k3arJKJ,UCnqj91wjXAT0bsmxF1fHWBA,Acción LAFC Con Armando Aguayo,"Cuando LAFC esta en la cancha, hay pasion, luc...",90,2026-08-13T18:43:58.156432+00:00
15,PLnNotX5RheZhNNDB6ht-m9WmJnRu0K7FA,UCnqj91wjXAT0bsmxF1fHWBA,LAFC2 Team Report,,7,2026-08-13T18:43:58.156432+00:00
16,PLnNotX5RheZiaLV36nvB8VmbmYbssdiFS,UCnqj91wjXAT0bsmxF1fHWBA,Black & Gold Weekly,,22,2026-08-13T18:43:58.156432+00:00
17,PLnNotX5RheZj4VjRrIUNlzIAiL1wwYgql,UCnqj91wjXAT0bsmxF1fHWBA,Sounds Of The Game,,17,2026-08-13T18:43:58.156432+00:00
18,PLnNotX5RheZjP-izPjFFTgAcfLtwT2-19,UCnqj91wjXAT0bsmxF1fHWBA,In Touch With Steve Cherundolo,,29,2026-08-13T18:43:58.156432+00:00
19,PLnNotX5RheZidytMHT_DmBWdr8_xMno5T,UCnqj91wjXAT0bsmxF1fHWBA,Behind The Crest 2022,,2,2026-08-13T18:43:58.156432+00:00
20,PLnNotX5RheZg9NGXtvjV27cMtY4MTl4HN,UCnqj91wjXAT0bsmxF1fHWBA,Talk Soccer W/ Dave Denholm,,2,2026-08-13T18:43:58.156432+00:00
21,PLnNotX5RheZhOZcvKmCT_-LdNe6SBIVw3,UCnqj91wjXAT0bsmxF1fHWBA,110 Football x LAFC | Season 2,,28,2026-08-13T18:43:58.156432+00:00
22,PLnNotX5RheZjlNrx_j-_h6dV4DGShfkie,UCnqj91wjXAT0bsmxF1fHWBA,Between Two Coaches,,4,2026-08-13T18:43:58.156432+00:00
23,PLnNotX5RheZi4OuIDvGcmspjbtFpg4fYV,UCnqj91wjXAT0bsmxF1fHWBA,Shootin' The Shot,,12,2026-08-13T18:43:58.156432+00:00
24,PLnNotX5RheZiTk6qqGMJ3RiHqwwE7kBGb,UCnqj91wjXAT0bsmxF1fHWBA,Staying Home,,3,2026-08-13T18:43:58.156432+00:00
25,PLnNotX5RheZjgcZqGEVhJ2M0TqisVDAdK,UCnqj91wjXAT0bsmxF1fHWBA,LAFC in 30,,12,2026-08-13T18:43:58.156432+00:00
26,PLnNotX5RheZjW9xeE9AKTcstfVhjtNafZ,UCnqj91wjXAT0bsmxF1fHWBA,#OnexOne,,2,2026-08-13T18:43:58.156432+00:00
27,PLnNotX5RheZh8FVCllTy5Q6yPCHOKZBJi,UCnqj91wjXAT0bsmxF1fHWBA,Behind The Crest,,53,2026-08-13T18:43:58.156432+00:00
28,PLnNotX5RheZjjSQVS-56dREeDDuUZeB4w,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Player Profiles,Get to know all the fascinating stories and co...,17,2026-08-13T18:43:58.156432+00:00
29,PLnNotX5RheZjBUYwMDN1t1Ua2FNxXY8dC,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Goal Rush Season 2,,4,2026-08-13T18:43:58.156432+00:00
30,PLnNotX5RheZgKw7SVam7NTYZlWmKYifxn,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Goal Rush Season 1,,4,2026-08-13T18:43:58.156432+00:00
31,PLnNotX5RheZiSTiDJdCWzweCVfq25fBOG,UCnqj91wjXAT0bsmxF1fHWBA,Faces Of LAFC,,11,2026-08-13T18:43:58.156432+00:00
32,PLnNotX5RheZhEJIpZOvp3KP3dgwo2gNhN,UCnqj91wjXAT0bsmxF1fHWBA,LAFC: Black & Gold Season 2,,8,2026-08-13T18:43:58.156432+00:00
33,PLnNotX5RheZhYmmkosftvUtcSTrDNQrrk,UCnqj91wjXAT0bsmxF1fHWBA,Taste Of LAFC,,5,2026-08-13T18:43:58.156432+00:00
34,PLnNotX5RheZhb38eCT2wq6NIyoiDoA518,UCnqj91wjXAT0bsmxF1fHWBA,2019 Match Recaps,,23,2026-08-13T18:43:58.156432+00:00
35,PLnNotX5RheZiIlKIEEEQfvESrMMjn5MtJ,UCnqj91wjXAT0bsmxF1fHWBA,Inside LAFC,Max Bretos pulls back the curtain each week wi...,230,2026-08-13T18:43:58.156432+00:00
36,PLnNotX5RheZiX3PxCUCVZjYtqOHpJg-w9,UCnqj91wjXAT0bsmxF1fHWBA,2019 Season Preview,,6,2026-08-13T18:43:58.156432+00:00
37,PLnNotX5RheZgH0BhRbFOxX7vEJq8h0APY,UCnqj91wjXAT0bsmxF1fHWBA,The Call Up | USMNT 2019 Camp,,3,2026-08-13T18:43:58.156432+00:00
38,PLnNotX5RheZhfs7oL6m_Row8_3I_ZCopZ,UCnqj91wjXAT0bsmxF1fHWBA,Explore BMO Stadium,,10,2026-08-13T18:43:58.156432+00:00
39,PLnNotX5RheZj8UeFT9AnyFjNNnfpoy0sF,UCnqj91wjXAT0bsmxF1fHWBA,TASTEMAKERS presented by Francis Ford Coppola ...,,2,2026-08-13T18:43:58.156432+00:00
40,PLnNotX5RheZhz78ivPu_NDsO6-6HI5mYm,UCnqj91wjXAT0bsmxF1fHWBA,Beita Time : Season 1,Quality time with LA’s favorite right-wing bac...,8,2026-08-13T18:43:58.156432+00:00
41,PLnNotX5RheZixZnDezkQBeeIzyxp29U6p,UCnqj91wjXAT0bsmxF1fHWBA,Beita Time,,23,2026-08-13T18:43:58.156432+00:00
42,PLnNotX5RheZgizYJXF4JtjarOSMGCjqOL,UCnqj91wjXAT0bsmxF1fHWBA,LAFC TAKING OFF presented by Delta,,3,2026-08-13T18:43:58.156432+00:00
43,PLnNotX5RheZhMWBb7R-uKWHHsOCT4bQmT,UCnqj91wjXAT0bsmxF1fHWBA,Community & Culture,,246,2026-08-13T18:43:58.156432+00:00
44,PLnNotX5RheZg3gAvUm0W7KKscrQ3OBbWg,UCnqj91wjXAT0bsmxF1fHWBA,LAFC 360,360 VR content from LAFC,11,2026-08-13T18:43:58.156432+00:00
45,PLnNotX5RheZiEFdylTp0V9TkRRmdl_dHe,UCnqj91wjXAT0bsmxF1fHWBA,Moments at BMO,,38,2026-08-13T18:43:58.156432+00:00
46,PLnNotX5RheZgEpuAhiSaDVkiyq02Wk6te,UCnqj91wjXAT0bsmxF1fHWBA,"Celebrities, Actors, Stars Experience LAFC Games",,39,2026-08-13T18:43:58.156432+00:00
47,PLnNotX5RheZjB3-OWq8-olbw5LGQFo5F0,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Essentials,,9,2026-08-13T18:43:58.156432+00:00
48,PLnNotX5RheZjQySOwMkcku5Du-8MUXsEj,UCnqj91wjXAT0bsmxF1fHWBA,Best of LAFC,,45,2026-08-13T18:43:58.156432+00:00
49,PLnNotX5RheZgBvW2-bcjzSBZf5Ro0wD0p,UCnqj91wjXAT0bsmxF1fHWBA,Features,Relive the biggest and best moments from the B...,347,2026-08-13T18:43:58.156432+00:00
50,PLnNotX5RheZiTDFQ5T7x_1wjIwFNXhjbu,UCnqj91wjXAT0bsmxF1fHWBA,Interviews,LAFC coaches and players speak to the media af...,479,2026-08-13T18:43:58.156432+00:00
51,PLnNotX5RheZiRf2xohUbifgThSBtJI8Sb,UCnqj91wjXAT0bsmxF1fHWBA,LAFC: Black & Gold,,22,2026-08-13T18:43:58.156432+00:00
52,PLnNotX5RheZh28uQp8x9MT7ujwzsluSoJ,UCnqj91wjXAT0bsmxF1fHWBA,LAFC All-Access,,32,2026-08-13T18:43:58.156432+00:00
53,PLnNotX5RheZhHCdJpuC7QXlVxZcB703Cq,UCnqj91wjXAT0bsmxF1fHWBA,Highlights,"Watch all the goals, skills, saves and action ...",824,2026-08-13T18:43:58.156432+00:00
54,PLnNotX5RheZhbMUJLsfA4AAE_o8c8Z3vq,UCnqj91wjXAT0bsmxF1fHWBA,Major News,,89,2026-08-13T18:43:58.156432+00:00
55,PLnNotX5RheZhmqL5RFHanQAZ2-S7PQC4o,UCnqj91wjXAT0bsmxF1fHWBA,BMO Stadium,,138,2026-08-13T18:43:58.156432+00:00

In [33]:
with open('../sql/video_playlists.sql') as f:
    query = f.read()

df = pd.read_sql_query(query, conn)
df

,video_id,playlist_id,playlist_title,position,playlist_size
0,w-PI8KXvIhQ,PLnNotX5RheZjW9xeE9AKTcstfVhjtNafZ,#OnexOne,0,2
1,poVf4jbckAk,PLnNotX5RheZjW9xeE9AKTcstfVhjtNafZ,#OnexOne,1,2
2,DIqaPD3ywuU,PLnNotX5RheZhOZcvKmCT_-LdNe6SBIVw3,110 Football x LAFC | Season 2,0,28
3,sDjigQ4rinI,PLnNotX5RheZhOZcvKmCT_-LdNe6SBIVw3,110 Football x LAFC | Season 2,1,28
4,39VWD19A8Bw,PLnNotX5RheZhOZcvKmCT_-LdNe6SBIVw3,110 Football x LAFC | Season 2,2,28
...,...,...,...,...,...
3477,C9ST9T0X-Ec,PLnNotX5RheZiJEQSDMwAs2BreZ2ymtyeu,The Vela Vault,22,27
3478,bpS_V2KZfm8,PLnNotX5RheZiJEQSDMwAs2BreZ2ymtyeu,The Vela Vault,23,27
3479,huc05WG2Sh8,PLnNotX5RheZiJEQSDMwAs2BreZ2ymtyeu,The Vela Vault,24,27
3480,2k0IfqHRSG0,PLnNotX5RheZiJEQSDMwAs2BreZ2ymtyeu,The Vela Vault,25,27
3481,UoA_3PAy_8g,PLnNotX5RheZiJEQSDMwAs2BreZ2ymtyeu,The Vela Vault,26,27